base: &common
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 3600  
    proxy: ç›´è¿ž
proxy-providers:

  # acyun:
  #   <<: *common  
  #   url: "https://145.acyunzz.top/api/v1/client/subscribe?token=847373ac53b4b30d98cf60a55ce13413"

  dingji:
    <<: *common  
    url: "https://gates.djjc.cfd/api/v1/client/subscribe?token=647b509e9b77b7ca676a2ee8fd49475f"

  shuiniu:
    <<: *common
    url: "https://wap.nnpy.org/niu/niu?token=f0a702dea124dae8c6bf1a868d0aea02"

  # åœ°é¼ :
  #   <<: *common
  #   url: "https://dwauhiaoawdibga.bikamanhua.top/sha/bi/gfw?token=098d11b6f84568f5f01184f7fd79688c"
    
  # lemao:
  #   <<: *common
  #   url: "https://zhongwang.zhongyasmart.com/a123/s/78c26a2de04b780881a02e2e1142a41b"

  # ikuuu:
  #   <<: *common
  #   url: "https://y3a12.no-mad-world.club/link/rRaA7U4kRKPwKvYs?clash=3&extend=1"
  #   health-check:
  #     enable: false
  
  è‡ªå»º:
    <<: *common
    url: "https://jd.xccfqjd.dpdns.org/xcc255733?sub"
    interval: 259200

  è‡ªå»º2:
    <<: *common
    url: "https://jd.x2gdl.qzz.io/xcc255733?sub"
    interval: 259200

proxies:
  - {name: ç›´è¿ž, type: direct}

# å…¨å±€é…ç½®  
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
# interface-name: enp6s18
log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true


sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"

tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack:
  - "udp://any:53"
  - "tcp://any:53"
  #dns-hijack: ["any:53", "tcp://any:53"]

  auto-route: true
  auto-redirect: false
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-hold-timeout: 300             #é»˜è®¤æ˜¯ 30 ç§’å°±å›žæ”¶ã€‚
  dns-cache-ttl: 86400                  #é»˜è®¤ç¼“å­˜åªæœ‰å‡ åˆ†é’Ÿã€‚
  fake-ip-pool-size-threshold: 5000     # æ± å­å‰©ä¸‹ 5000 ä¸ªåœ°å€æ—¶å°±å¼€å§‹æå‰åˆ·æ–°ï¼ˆé»˜è®¤æ˜¯ 512ï¼‰
  fake-ip-pool-refresh-interval: 60     # æ¯ 60 ç§’å¼ºåˆ¶åˆ·æ–°ä¸€æ¬¡è¿‡æœŸ Fake-IPï¼ˆé»˜è®¤ 300 ç§’ï¼‰
  fake-ip-prefetch: 100                 # æ¯æ¬¡åˆ·æ–°æå‰å›žæ”¶ 100 ä¸ªæœ€è€çš„åœ°å€ï¼ˆé»˜è®¤ 0ï¼‰
  fake-ip-filter-mode: blacklist
  fake-ip-filter:    
    - "rule-set:private_domain,cn_domain"
    - "time.*.com"
    - "+.market.xiaomi.com"

    #pako
    - "+.lan"
    - "connect.rom.miui.com"
    - "+.miwifi.com"
    - "+.ntp.org"
    - "+.u-tools.cn"
    - "+.mediatek.com"
    - "+.cfprefer1.xyz"
    - "+.wetab.link"
    - "+.tyasaka.xyz"
    # QQ
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    # WeChat
    - "localhost.work.weixin.qq.com"
    - "+.weixin.qq.com"
    - "+.wechat.com"
    # Windows
    - "time.windows.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "+.wpsmail.net"
    - "+.henzanapp.com"
    - "+.pconline.com.cn"
    #ai
    - "+.cn"
    - "+.com.cn"
    - "+.net.cn"
    - "+.org.cn"
    - "+.gov.cn"
    - "+.baidu.com"
    - "+.taobao.com"
    - "+.tmall.com"
    - "+.jd.com"
    - "+.pinduoduo.com"
    - "+.qq.com"
    - "+.weibo.com"
    - "+.sina.com.cn"
    - "+.sohu.com"
    - "+.bilibili.com"
    - "+.douyin.com"
    - "+.kuaishou.com"
    - "+.ixigua.com"
    - "+.meituan.com"
    - "+.dianping.com"
    - "+.alipay.com"
    - "+.zhihu.com"
    - "+.163.com"
    - "+.126.com"
    - "+.youku.com"
    - "+.iqiyi.com  iqiyi.com"
    - "+.tudou.com"
    - "+.tencent.com"
    - "+.mi.com"
    - "+.xiaomi.com"
    - "+.huawei.com"
    - "+.oppo.com"
    - "+.vivo.com"
    - "+.360.cn"
    - "+.sogou.com"
    - "+.smzdm.com"
    - "+.autohome.com.cn"
    - "+.ctrip.com"
    - "+.58.com"
    - "+.ganji.com"
    - "+.liepin.com"
    - "+.zhipin.com"
    - "+.douyu.com"
    - "+.huya.com"
    - "+.yy.com"
    - "+.acfun.cn"
    - "+.top"
    - "+.xyz"
    - "+.vip"
    - "+.wang"
    - "+.club"
    - "+.shop"
    - "+.store"
    - "+.online"
    - "+.site"
    - "+.tech"
    - "+.fun"
    - "+.ink"
    - "+.pub"
    - "+.icu"
    - "+.ltd"
    - "+.work"
    - "+.live"
    
    - "*"
  default-nameserver:
    [223.5.5.5, 119.29.29.29, 114.114.114.114]
  direct-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  direct-nameserver-follow-policy: false  

  proxy-server-nameserver: 
    [119.29.29.29, 223.5.5.5, 114.114.114.114]

  nameserver-policy:

    '+.nbvpn.top': [223.5.5.5, 119.29.29.29]
    '+.baidu.com': '114.114.114.114'
    #openai
    "*.openai.com":
      - https://1.1.1.1/dns-query
    "*.oaiusercontent.com":
      - https://1.1.1.1/dns-query
    "*.auth0.com":
      - https://1.1.1.1/dns-query
    "*.intercom.io":
      - https://1.1.1.1/dns-query
    "*.sentry.io":
      - https://1.1.1.1/dns-query

    "rule-set:private_domain,cn_domain":
      - 223.5.5.5
      - 119.29.29.29

    "rule-set:geolocation-!cn":

      - https://1.1.1.1/dns-query
      - https://8.8.8.8/dns-query

  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114

pr: &pr {type: select, proxies: [ ðŸ”¯æ—¥æœ¬æ•…è½¬,ðŸ”¯ç¾Žå›½æ•…è½¬, ðŸ‡¯ðŸ‡µæ—¥æœ¬èŠ‚ç‚¹,ðŸ‡ºðŸ‡¸ç¾Žå›½èŠ‚ç‚¹, ðŸ‡­ðŸ‡°é¦™æ¸¯èŠ‚ç‚¹,ðŸ‡¹ðŸ‡¼å°æ¹¾èŠ‚ç‚¹, ðŸ‡¸ðŸ‡¬æ–°åŠ å¡èŠ‚ç‚¹,ðŸ‡°ðŸ‡·éŸ©å›½èŠ‚ç‚¹,ðŸŒå…¨éƒ¨èŠ‚ç‚¹,ðŸŒå°ä¼—åœ°åŒº,ç›´è¿ž]}

#â™»ï¸é¦™æ¸¯è‡ªåŠ¨, â™»ï¸æ–°åŠ å¡è‡ªåŠ¨, â™»ï¸æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ç¾Žå›½è‡ªåŠ¨, â™»ï¸è‡ªåŠ¨é€‰æ‹©,ðŸ”¯éŸ©å›½æ•…è½¬,,ðŸ”¯æ–°åŠ å¡æ•…è½¬,ðŸ”¯é¦™æ¸¯æ•…è½¬,ðŸ”¯å°æ¹¾æ•…è½¬,ðŸ”„ä¸­è½¬,ðŸ§ è‡ªå»º
proxy-groups:

  #å¸¸ç”¨
  - {name: ðŸš€é»˜è®¤ä»£ç†, <<: *pr}
  
  - name: ðŸ”¯æ—¥æœ¬æ•…è½¬
    type: fallback
    include-all: true
    tolerance: 20
    interval: 1200
    filter: "(?i)^(?!.*(ç¾Ž|å¾·å›½|ä¸­è½¬)).*(æ—¥|jp|japan|NRT)"

  - name: ðŸ”¯ç¾Žå›½æ•…è½¬
    type: fallback
    include-all: true
    tolerance: 20
    interval: 1200
    filter: "(?i)^(?!.*(æ¸¯|å°|éŸ©|æ–°åŠ å¡|æ—¥|ä¸­è½¬)).*(ç¾Ž|us|unitedstates|united states|èŠåŠ å“¥|ORD|æ´›æ‰çŸ¶|LAX|åœ£ä½•å¡ž|SJC)"


  #åº”ç”¨ç»„
  - {name: â–¶ï¸YouTube, <<: *pr}
  - {name: ðŸ‡¬Google, <<: *pr}  
  - {name: ðŸ¤–Chatgpt, <<: *pr}
  - {name: âœˆï¸Telegram, <<: *pr}
  - {name: ðŸŸæ¼ç½‘ä¹‹é±¼, <<: *pr}


  # èŠ‚ç‚¹åœ°åŒºç»„
  - name: ðŸ‡¯ðŸ‡µæ—¥æœ¬èŠ‚ç‚¹
    type: select
    include-all: true
    filter: "(?i)æ—¥|jp|japan|NRT"

  - name: ðŸ‡ºðŸ‡¸ç¾Žå›½èŠ‚ç‚¹
    type: select
    include-all: true
    filter: "(?i)ç¾Ž|us|unitedstates|united states|èŠåŠ å“¥|ORD|æ´›æ‰çŸ¶|LAX|åœ£ä½•å¡ž|SJC"

  - name: ðŸ‡­ðŸ‡°é¦™æ¸¯èŠ‚ç‚¹
    type: select
    include-all: true
    filter: "(?i)æ¸¯|HK|Hong"
    exclude-filter: "(?i)(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾Ž)"

  - name: ðŸ‡¹ðŸ‡¼å°æ¹¾èŠ‚ç‚¹
    type: select
    include-all: true
    filter: "(?i)å°æ¹¾|tw|taiwan|å°åŒ—|å°"
  
  - name: ðŸ‡¸ðŸ‡¬æ–°åŠ å¡èŠ‚ç‚¹
    type: select
    include-all: true
    filter: "(?i)æ–°åŠ å¡|å¡|ç‹®åŸŽ|SG|Singapore|SIN"
    exclude-filter: "(?i)(å°|æ—¥|éŸ©|æ·±|ç¾Ž|é¦™æ¸¯)"
  
  - name: ðŸ‡°ðŸ‡·éŸ©å›½èŠ‚ç‚¹
    type: select
    include-all: true
    filter: "(?i)éŸ©|éŸ©å›½|kr|korea|é¦–å°”"

  # å°ä¼—åœ°åŒºç»„
  - name: ðŸŒå°ä¼—åœ°åŒº
    type: select
    include-all: true
    filter: "(?i)(è‹±å›½|uk|united kingdom|è‹±æ ¼å…°|ä¼¦æ•¦|Russia|ä¿„|å¾·å›½|de|germany|æŸæž—|æ³•å…°å…‹ç¦|FRA|å°åº¦|india|delhi|mumbai|å­Ÿä¹°|å¾·é‡Œ|æ³•å›½|fr|france|å·´é»Ž|åŠ æ‹¿å¤§|ca|canada|å¤šä¼¦å¤š|æ¸©å“¥åŽ|å¢¨è¥¿å“¥|mx|mexico|ç‘žå…¸|se|sweden|æ–¯å¾·å“¥å°”æ‘©|æ¾³å¤§åˆ©äºš|au|australia|æ‚‰å°¼|å¢¨å°”æœ¬|å·´è¥¿|br|brazil|é‡Œçº¦|åœ£ä¿ç½—|è¿ªæ‹œ|uae|é˜¿è”é…‹|éžæ´²|africa|å—éž|å°¼æ—¥åˆ©äºš|å°å°¼|indonesia|é›…åŠ è¾¾|è²å¾‹å®¾|ph|philippines|é©¬å°¼æ‹‰|æ³°å›½|th|thailand|æ›¼è°·|ä¹Œå…‹å…°|ua|ukraine|åŸºè¾…|å¸Œè…Š|gr|greece|é›…å…¸|åœŸè€³å…¶|tr|turkey|ä¼Šæ–¯å¦å¸ƒå°”|è·å…°|nl|netherlands|é˜¿å§†æ–¯ç‰¹ä¸¹|AMS|è¶Šå—|èŠ¬å…°|è¥¿ç­ç‰™|æ¾³)"
    exclude-filter: "(?i)(ç›´è¿ž|ç¾¤ç»„|ä»¥ä¸‹|å®˜ç½‘|è®¢é˜…|æµé‡|é‡ç½®|å¥—é¤|åˆ°æœŸ|åœ°å€|fraud)"

  # æ•…éšœè½¬ç§»ç»„
  # - name: ðŸ”¯æ–°åŠ å¡æ•…è½¬
  #   type: fallback
  #   include-all: true
  #   tolerance: 20
  #   interval: 1800
  #   filter: "(?i)(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸŽ|SG|Singapore|SIN))^((?!(å°|æ—¥|éŸ©|æ·±|ç¾Ž)).)*$"

  # - name: ðŸ”¯é¦™æ¸¯æ•…è½¬
  #   type: fallback
  #   include-all: true
  #   tolerance: 20
  #   interval: 1800
  #   filter: "(?i)(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾Ž)).)*$"

  # - name: ðŸ”¯éŸ©å›½æ•…è½¬
  #   type: fallback
  #   include-all: true
  #   tolerance: 20
  #   interval: 1800
  #   filter: "(?i)éŸ©|éŸ©å›½|kr|korea|é¦–å°”"

  # - name: ðŸ”¯å°æ¹¾æ•…è½¬
  #   type: fallback
  #   include-all: true
  #   tolerance: 20
  #   interval: 1800
  #   filter: "(?i)å°æ¹¾|tw|taiwan|å°åŒ—|å°"

  # å…¨éƒ¨èŠ‚ç‚¹
  - name: ðŸŒå…¨éƒ¨èŠ‚ç‚¹
    type: select
    include-all: true
    filter: "^((?!(ç›´è¿ž|ç¾¤ç»„|ä»¥ä¸‹|å®˜ç½‘|è®¢é˜…|æµé‡|é‡ç½®|å¥—é¤|åˆ°æœŸ|å®˜æ–¹|åœ°å€)).)*"

  # ä¸­è½¬
  # - name: ðŸ”„ä¸­è½¬
  #   type: fallback
  #   include-all: true
  #   tolerance: 20
  #   interval: 1800
  #   filter: "(?=.*(ä¸­è½¬))^((?!(ç›´è¿ž|ç¾¤ç»„|ä»¥ä¸‹|å®˜ç½‘|è®¢é˜…|æµé‡|é‡ç½®|å¥—é¤|åˆ°æœŸ|å®˜æ–¹|åœ°å€)).)*"

  # - name: ðŸ§ è‡ªå»º
  #   type: url-test
  #   include-all: true
  #   tolerance: 20
  #   interval: 1800
  #   filter: "(?i)åä»£ä¼˜é€‰|æ–¹ä¼˜é€‰"

  - name: âŒæ— ç”¨
    type: select
    include-all: true
    filter: "(?i)(ç¾¤ç»„|ä»¥ä¸‹|å®˜ç½‘|è®¢é˜…|æµé‡|é‡ç½®|å¥—é¤|åˆ°æœŸ|å®˜æ–¹|åœ°å€)"
    exclude-filter: "(?i)(è‡ªå»º|å®˜æ–¹ä¼˜é€‰)"
  
  # è‡ªåŠ¨æµ‹é€Ÿç»„
  #- {name: â™»ï¸é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾Ž)).)*$"}
  #- {name: â™»ï¸æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾Ž)).)*$" }
  #- {name: â™»ï¸æ–°åŠ å¡è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸŽ|SG|Singapore|SIN))^((?!(å°|æ—¥|éŸ©|æ·±|ç¾Ž)).)*$"}
  #- {name: â™»ï¸ç¾Žå›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(ç¾Ž|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  #- {name: â™»ï¸è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(ç›´è¿ž|ç¾¤ç»„|ä»¥ä¸‹|å®˜ç½‘|è®¢é˜…|æµé‡|é‡ç½®|å¥—é¤|åˆ°æœŸ|å®˜æ–¹|åœ°å€)).)*$"} 

  - {name: ðŸ™GitHub, <<: *pr}
  - {name: ðŸŽµTikTok, <<: *pr}
  # - {name: â˜ï¸OneDrive, <<: *pr}
  # - {name: ðŸ’»Microsoft, <<: *pr}
  # - {name: ðŸŽ¥NETFLIX, <<: *pr}
  # - {name: ðŸ’¶PayPal, <<: *pr}

# è§„åˆ™åŒ¹é…
rules:  
  - DOMAIN-KEYWORD,ping0.cc,ðŸŸæ¼ç½‘ä¹‹é±¼
  - RULE-SET,geolocation-!cn_extra,ðŸš€é»˜è®¤ä»£ç†
  - RULE-SET,ai_extra,ðŸ¤–Chatgpt
  - RULE-SET,direct_extra,ç›´è¿ž
  - RULE-SET,JP_region,ðŸ‡¯ðŸ‡µæ—¥æœ¬èŠ‚ç‚¹
  - RULE-SET,US_region,ðŸ‡ºðŸ‡¸ç¾Žå›½èŠ‚ç‚¹
  - RULE-SET,twitter_domain,ðŸ”¯æ—¥æœ¬æ•…è½¬

  - RULE-SET,private_ip,ç›´è¿ž
  - RULE-SET,private_domain,ç›´è¿ž
  - RULE-SET,proxylite,ðŸš€é»˜è®¤ä»£ç†

  - RULE-SET,ai,ðŸ¤–Chatgpt
  - RULE-SET,github_domain,ðŸ™GitHub
  - RULE-SET,youtube_domain,â–¶ï¸YouTube
  - RULE-SET,google_domain,ðŸ‡¬Google  
  - RULE-SET,apple_domain,ç›´è¿ž
  - RULE-SET,tiktok_domain,ðŸŽµTikTok
  - RULE-SET,telegram_domain,âœˆï¸Telegram

  - RULE-SET,onedrive_domain,ðŸš€é»˜è®¤ä»£ç†
  - RULE-SET,microsoft_domain,ðŸš€é»˜è®¤ä»£ç†
  - RULE-SET,netflix_domain,ðŸš€é»˜è®¤ä»£ç† 
  - RULE-SET,paypal_domain,ðŸš€é»˜è®¤ä»£ç†
  # - RULE-SET,onedrive_domain,â˜ï¸OneDrive
  # - RULE-SET,microsoft_domain,ðŸ’»Microsoft
  ##æ³¨é‡Šä¸ºå•¥ä¸å¥½ç”¨
  # - RULE-SET,paypal_domain,ðŸ’¶PayPal

  - RULE-SET,apple_ip,ç›´è¿ž,no-resolve
  - RULE-SET,google_ip,ðŸ‡¬Google,no-resolve 

  - RULE-SET,netflix_ip,ðŸš€é»˜è®¤ä»£ç†,no-resolve #æˆ‘ä¸æ˜Žç™½

  - RULE-SET,telegram_ip,âœˆï¸Telegram,no-resolve
  - RULE-SET,geolocation-!cn,ðŸš€é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ç›´è¿ž
  - RULE-SET,cn_ip,ç›´è¿ž
  - MATCH,ðŸŸæ¼ç½‘ä¹‹é±¼
 
# è§„åˆ™é›†
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  ai_extra:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: "https://gist.githubusercontent.com/JSCSZZSS/1da529e6e0569447b576d9b5b4fd68fe/raw/ai_extra.list"
  direct_extra:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: "https://gist.githubusercontent.com/JSCSZZSS/d0484188fc09a343ee01c882025e09e1/raw/direct_extra.list"  
  geolocation-!cn_extra:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: "https://gist.githubusercontent.com/JSCSZZSS/af551de764b4032a5d39495e7db1b9cb/raw/geolocation-!cn_extra.list"
  US_region:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: "https://gist.githubusercontent.com/JSCSZZSS/82008d3f19c2b6f14fb0cbdb14714bac/raw/USregion.list"  
  JP_region:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: "https://gist.githubusercontent.com/JSCSZZSS/dd805bdf7de389288ab677ca8e3675f0/raw/JPregion.gist"  
        
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  
  ai: {  <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  twitter_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs"}  
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  

  private_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
